---
name: 'Clase 2: Formularios y posicionamiento'
locale: es
type: practice
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 11
- 12
- 15
- 13
- 14
